Repository huangyanhui/lawDocSearch, pull requests merged in 2018-03, with the labels that each got.

#12 :sparkles: [功能 Feature] 文书详细页面
  lawDoc/urls.py
  lawDoc/views.py
  lawDocSearch/urls.py
  templates/resultDetail.html
  templates/searchresult.html
Labels: enhancement

#13 :lipstick: [Refractory 重构] 登录模块
  account/views.py
  lawDoc/views.py
  manage.py
  static/css/index.css
  static/css/login_style.css
  static/css/register_style.css
  static/img/firstback.jpg
  templates/account/login.html
  templates/account/register.html
  templates/account/status.html
  templates/index.html
Labels: enhancement

#20 上传功能
  lawDoc/models.py
  lawDoc/views.py
  lawDocSearch/urls.py
  static/css/upload.css
  templates/upload/index.html
  upload/__init__.py
  upload/admin.py
  upload/apps.py
  upload/migrations/__init__.py
  upload/models.py
  upload/tests.py
  upload/urls.py
  upload/utils/elastic_search_utils.py
  upload/views.py
  utils/__init__.py
  utils/elastic_search.py
  utils/read_files.py
  utils/text_process.py
  utils/wrapper.py
Labels: enhancement

#24 :bug: 查询限制次数
  account/migrations/0002_auto_20180309_1147.py
  account/migrations/0003_auto_20180309_1150.py
  account/models.py
  account/views.py
  lawDoc/views.py
  templates/index.html
  utils/read_files.py
Labels: bug

#27 :bug: 修改bug
  account/migrations/0004_user_identity.py
  account/models.py
  account/views.py
  lawDoc/views.py
  static/css/login_style.css
  templates/account/login.html
  templates/index.html
  templates/tips.html
  upload/views.py
Labels: bug

#28 :bug: 首页 session 错误
  lawDoc/views.py
Labels: bug

#31 :bug: 修复小标签显示（表达）错误
  lawDoc/views.py
  templates/result.html
  templates/searchresult.html
Labels: bug

#33 :bug: 修改 上传 bug
  corpus/__init__.py
  corpus/composite_word.py
  corpus/jieba_ex.py
  corpus/parser.py
  corpus/run.py
  lawDoc/views.py
  upload/views.py
Labels: bug

#37 Account模块测试
  account/tests.py
Labels: good first issue

#39 Pc
  lawDoc/tests.py
Labels: good first issue

#41 :bug: 修改 bug
  account/migrations/0005_user_is_active.py
  account/models.py
  account/urls.py
  account/views.py
  lawDoc/views.py
  lawDocSearch/settings.py
  static/download/pdf.html
  templates/account/login.html
  templates/account/register.html
  templates/index.html
  utils/MyEmail.py
Labels: bug
